apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: configure
  description: Seamlessly configure applications with either flags or JSON
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
